### PR TITLE
[JS][TS][PHP-Template] Scope fixed

### LINKED ISSUE #25: Port language: javascript

### LINKED ISSUE #37: Port language: typescript

### LINKED ISSUE #40: Port language: php-template

### PR DESCRIPTION
**Pull request by yescorp**
- Resolves #25 
- Resolves #37 
- Resolves #40

### CODE REVIEW

File: highlighting/lib/languages/common/nulls.dart
Comment (alexeyinkin) [inline highlighting/lib/languages/common/nulls.dart:1]: If this file is not meant to be imported by the library's clients directly, it should be under `src`.

Same with `common/callbacks.dart` and `common/mathematica_symbols.dart`.

File: highlighting/lib/languages/1c.dart [hunk 1]
```diff
@@ -2,6 +2,7 @@
 
 import '../src/mode.dart';
 import '../src/common_modes.dart';
+import 'common/nulls.dart';
```
Comment (alexeyinkin) [inline highlighting/lib/languages/1c.dart:5]: To avoid 193 changed files when we change imports in modes, I suggest making a single file like `src/mode_imports.dart` and export these 3 files there. Then in all modes only import this single file.

This way we can also get rid of a condition when importing `common/callbacks.dart`.

File: highlighting/lib/src/extension/compiler_extensions.dart [hunk 2]
```diff
@@ -1,3 +1,5 @@
+import 'package:highlighting/languages/common/nulls.dart';
```
Comment (alexeyinkin) [inline highlighting/lib/src/extension/compiler_extensions.dart:1]: Relative import.

File: highlighting/lib/src/extension/compiler_extensions.dart [hunk 3]
```diff
@@ -14,8 +16,9 @@ void skipIfHasPrecedingDot(DomainRegexMatch match, Response response) {
 }
 
 void scopeClassName(Mode mode, [Mode? parent]) {
```
Comment (alexeyinkin) [inline highlighting/lib/src/extension/compiler_extensions.dart:18]: Looks like all calls to this have `parent`.
```suggestion
void scopeClassName(Mode mode, Mode? parent) {
```

File: highlighting/lib/src/extension/compiler_extensions.dart [hunk 4]
```diff
@@ -14,8 +16,9 @@ void skipIfHasPrecedingDot(DomainRegexMatch match, Response response) {
...
-  if (mode.className != null && mode.className != '') {
-    mode.scope = mode.className;
+  if ((mode.className != null && mode.className != '') ||
+      mode.getRawClassName() == preserveNullString) {
+    mode.scope = mode.className ?? preserveNullString;
     mode.className = null;
```
Comment (alexeyinkin) [inline highlighting/lib/src/extension/compiler_extensions.dart:22]: 1. Looks like the test for `''` is not in the original HighlightJS.
2. Try to simplify this.

File: tool/src/porting.ts [hunk 5]
```diff
@@ -28,6 +28,13 @@ export function generateMode(
     }
 
     switch (k) {
+      case "className":
```
Comment (alexeyinkin) [inline tool/src/porting.ts:31]: Check if `scope` should be handled the same way.

**Review by alexeyinkin — CHANGES_REQUESTED** [review]

File: highlighting/lib/languages/1c.dart (hunk 1 above)
Comment (alexeyinkin) [reply highlighting/lib/languages/1c.dart]: ?

File: highlighting/lib/src/language_definition_parts/callbacks.dart [hunk 6]
```diff
@@ -1,8 +1,8 @@
-import 'package:highlighting/languages/common/mathematica_symbols.dart';
```
Comment (alexeyinkin) [inline highlighting/lib/src/language_definition_parts/callbacks.dart:1]: 1. Move everything from `language_definition_parts` directory to `src/`.
2. Move `mathematica_symbols.dart` to `src/languages`.

File: highlighting/lib/src/mode.dart [hunk 7]
```diff
@@ -137,11 +152,14 @@ class Mode {
...
-  });
+    dynamic className,
+    dynamic scope,
+  })  : _className = className,
+        _scope = scope;
 
   static Mode inherit(Mode a, [Mode? b]) {
     b ??= Mode();
-    return Mode()
+    var toReturn = Mode()
```
Comment (alexeyinkin) [inline highlighting/lib/src/mode.dart:162]:
```suggestion
    final result = Mode()
```

File: highlighting/lib/src/extension/compiler_extensions.dart [hunk 8]
```diff
@@ -13,9 +14,13 @@ void skipIfHasPrecedingDot(DomainRegexMatch match, Response response) {
   }
 }
 
-void scopeClassName(Mode mode, [Mode? parent]) {
-  if (mode.className != null && mode.className != '') {
-    mode.scope = mode.className;
+void scopeClassName(Mode mode, Mode? parent) {
+  final rawClassName = mode.getRawClassName();
+  final classNameIsMeaningful = rawClassName != null;
```
Comment (alexeyinkin) [inline highlighting/lib/src/extension/compiler_extensions.dart:19]:
```suggestion
  final classNameIsSignificant = rawClassName != null;
```

File: highlighting/lib/src/extension/compiler_extensions.dart [hunk 9]
```diff
@@ -13,9 +14,13 @@ void skipIfHasPrecedingDot(DomainRegexMatch match, Response response) {
...
+  final classNameIsExplicitNull = rawClassName == overwritingNullString;
```
Comment (alexeyinkin) [inline highlighting/lib/src/extension/compiler_extensions.dart:20]: Try to delete this and add a comment why `mode.className` below can be `null`.

File: highlighting/lib/src/extension/compiler_extensions.dart [hunk 10]
```diff
@@ -13,9 +14,13 @@ void skipIfHasPrecedingDot(DomainRegexMatch match, Response response) {
   }
 }
 
-void scopeClassName(Mode mode, [Mode? parent]) {
-  if (mode.className != null && mode.className != '') {
-    mode.scope = mode.className;
+void scopeClassName(Mode mode, Mode? parent) {
```
Comment (alexeyinkin) [inline highlighting/lib/src/extension/compiler_extensions.dart:17]:
```suggestion
void scopeClassName(Mode mode) {
```

**Review by alexeyinkin — CHANGES_REQUESTED** [review]

**Review by alexeyinkin — APPROVED** [review]
